### ISSUE TITLE
Add some explanations

### ISSUE THREAD

**Issue by awattez** [NisaarAgharia/AI-Avatars#1]
Hi,
you have made a certain number of copies and pastes from your drive to the training images directory.  Is it possible to provide access to this dataset or explain what it contains?

https://github.com/NisaarAgharia/AI-Avatars/blob/be4cd862279f5952a51644686d834004f4d1be05/nisaar_dreambooth_custom_Stable_Diffusion.py#L89

**Comment by NisaarAgharia** [comment]
nope
